name: Release

on:
    push:
        tags:
            - '*.*.*'

jobs:
    build:
        runs-on: ubuntu-latest
        container: mcr.microsoft.com/dotnet/sdk:5.0
        steps:
            -   uses: actions/checkout@v2.3.4
            -   name: Prepare
                id: prep
                run: |
                    VERSION=${GITHUB_REF#refs/tags/}
                    echo ::set-output name=version::${VERSION}
            -   name: Create packages
                run: dotnet pack -c Release /p:Version=${{ steps.prep.outputs.version }} -o $(pwd)/packages
            -   name: Pack library
                run: dotnet pack -c Release /p:Version=${{ steps.prep.outputs.version }} -o packages
            -   name: Publish nuget package
                run: dotnet nuget push packages/*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }}
                    
